### ISSUE TITLE
[Question] What is the best way to mock presenters?

### ISSUE THREAD

**Issue by geralt-encore** [ivacf/archi#2]
Hey! First of all, thank you for a great sample! I  have a question according to presenters mocking. Some time I go I adopted architecture proposed by @hitherejoe in his Android-Boilerplate project. He is mocking his dependencies for Espresso tests by providing different dagger components and looks like this approach doesn't suit well for your MVP example, because the simplest way - just to mock presenter instead of your app dependencies. So, what is the best way to do it in your opinion?
I will much appreciate your answer. Thank you!

**Comment by ivacf** [comment]
Hi, you can use exaclty the same approach as joe's boilerplate project with the MVP example. Why do you think it doesn't suit it well? When testing presenters you will normally have to mock the model and the view. 

When I have some free time I'll add Dagger to the MVP and MVVM examples.

**Comment by geralt-encore** [comment]
Thank you for the reply! Testing presenters is clear for me, but I am talking about testing views and mocking presenters. I think it doesn't suit well because you need to create Dagger modules and components for every activity/fragment in order to inject presenters and then inject mock presenters for testing purposes. Do I get it wrong? Example with Dagger would be really nice. Or if you can explain to me how to do it properly I can try to add it myself.

**Comment by ivacf** [comment]
I understand your question now. You should be able to mock the presenter in the same way that you mock any other class. If you use Dagger, you can create a module that provides presenters and then another module for your tests that provides mock presenters created with Mockito. 

I generally don't mock the presenters though. I usually don't write unit tests for the view layer because they are a bit of a pain. And when using Espresso, I only mock the model layer.

**Comment by geralt-encore** [comment]
Now I see your point. Thank you again for a great sample and your answers
